@import Foundation;

typedef NSString *MBXTestingSupportNotification NS_TYPED_ENUM;

extern const MBXTestingSupportNotification MBXTestingSupportNotificationExampleComplete;
extern const MBXTestingSupportNotification MBXTestingSupportNotificationMapViewStyleLoaded;
extern const MBXTestingSupportNotification MBXTestingSupportNotificationMapViewRendered;

FOUNDATION_EXTERN void testingSupportPostNotification(MBXTestingSupportNotification name);
