# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "2.105.0"
opt_out_usage

default_platform :ios

platform :ios do
  before_all do
    update_fastlane
  end

  desc "Runs all the tests"
  lane :test do
    cocoapods
    scan
  end

  desc "Submit a new build to Apple TestFlight."
  lane :beta do
    match(git_url: ENV["MATCH_REPO"], username: ENV["MATCH_USER"], type: "appstore", readonly: true)
    increment_build_number(build_number: latest_testflight_build_number + 1)
    gym(scheme: "Examples", include_bitcode: true)
    pilot(
      changelog: changelog_from_git_commits(commits_count: 5, pretty: "- %s. (%an, %cd)"),
      skip_waiting_for_build_processing: false
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
